{
 "title": "Mailboxes",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "mailboxname", "query": { "query": "label_values(mailboxname)" } }
  ]
 },
 "panels": [
  {
   "title": "imap-mailstat-exporter version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(mailstat_info[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "errors in last 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(mailstat_up[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "maximum fetch durations in the last 24 hours",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(mailstat_fetch_duration_seconds[24h])) by (mailboxname)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "$mailboxname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }, "repeat": "mailboxname" },
  {
   "title": "total mails in Inbox of $mailboxname",
   "type": "stat",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(mailstat_mails_all{mailboxname=\"$mailboxname\", mailboxfoldername=\"INBOX\"}[10m])",
     "legendFormat": "{{mailboxname}}_{{mailboxfoldername}}"
    }
   ]
  },
  {
   "title": "total unread mails Inbox of $mailboxname",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(mailstat_mails_unseen{mailboxname=\"$mailboxname\", mailboxfoldername=\"INBOX\"}[10m])",
     "legendFormat": "{{mailboxname}}_{{mailboxfoldername}}"
    }
   ]
  },
  {
   "title": "total spam mails in $mailboxname",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(mailstat_mails_all{mailboxname=\"$mailboxname\", mailboxfoldername=\"INBOX_Spam\"}[10m])",
     "legendFormat": "{{mailboxname}}_{{mailboxfoldername}}"
    }
   ]
  },
  {
   "title": "time since oldest unread mail in Inbox in $mailboxname",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - last_over_time(mailstat_mails_oldest_unseen_timestamp{mailboxname=\"$mailboxname\", mailboxfoldername=\"INBOX\"}[10m])",
     "legendFormat": "{{mailboxname}}_{{mailboxfoldername}}"
    }
   ]
  },
  {
   "title": "metric fetch duration for $mailboxname",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(mailstat_fetch_duration_seconds{mailboxname=\"$mailboxname\"}[10m])",
     "legendFormat": "{{mailboxname}}_{{mailboxfoldername}}"
    }
   ]
  },
  {
   "title": "unread mails in Inbox of $mailboxname",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 10, "y": 19 },
   "targets": [
    {
     "expr": "last_over_time(mailstat_mails_unseen{mailboxname=\"$mailboxname\", mailboxfoldername=\"INBOX\"}[10m])",
     "legendFormat": "{{mailboxfoldername}}"
    }
   ]
  },
  {
   "title": "storage quota used for $mailboxname",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(mailstat_storage_quota_used_bytes{mailboxname=\"$mailboxname\"}[10m]) * 100 / last_over_time(mailstat_storage_quota_avail_bytes{mailboxname=\"$mailboxname\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}